project_id = "vllpaaomsmuhcngiikhf"

[functions.send-contact-email]
verify_jwt = false

[functions.send-trial-email]
verify_jwt = false

[functions.send-roi-email]
verify_jwt = false

[functions.ai-context]
verify_jwt = false

[functions.send-blog-lead-email]
verify_jwt = false

[functions.optimize-blog-seo]
verify_jwt = false

[functions.generate-blog-post]
verify_jwt = false

[functions.content-scheduler]
verify_jwt = false

[functions.send-content-notification]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false